### ISSUE TITLE
How to install qpdf.?

### ISSUE THREAD

**Issue by manprajapat** [nrhirani/node-qpdf#1]
how we can install qpdf in node js?
can you tell me the process after downloading it from sourceforge?

**Comment by nrhirani** [comment]
You can download qpdf 6.0.0 from [here](https://sourceforge.net/projects/qpdf/files/qpdf/6.0.0/) and the install instruction is present in the [qpdf manual](http://qpdf.sourceforge.net/files/qpdf-manual.html) **2.2 Build Instructions** section which varies according to the OS that you are using.

**Comment by nrhirani** [comment]
Closing this issue. If you need further help let me know.
