### ISSUE TITLE
can you please help

### ISSUE THREAD

**Issue by imranmunirawan** [nrhirani/node-qpdf#10]
spawn qpdf ENOENT error

**Comment by nrhirani** [comment]
@imranmunirawan Can you be more specific?

**Comment by imranmunirawan** [comment]
There is spawn keyword is unidentifiable by compiler

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nrhirani** [comment]
Do you have node.js installed? It is a [dependency](https://github.com/nrhirani/node-qpdf#dependencies).

**Comment by imranmunirawan** [comment]
Yes  Nodejs is installed and running well, v 10.12.0, what are the dependencies of this library qpdf?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by imranmunirawan** [comment]
1. npm install (‘node-qpdf’)
2.[Image]

3. Got the issue spawn qpdf ENOENT.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nrhirani** [comment]
Can't see the image that has been added in the previous comment. 

Can you run `qpdf` on the terminal and check if it is installed correctly? If not please follow the instructions present in the readme and the qpdf manual.

**Comment by imranmunirawan** [comment]
> qpdf
{ encrypt: [Function], decrypt: [Function], command: 'qpdf' }

**Comment by imranmunirawan** [comment]
but when i implement this code
var qpdf = require('node-qpdf');

var options = {
    keyLength: 128,
    password: '15464aerewrwrwf'
}

qpdf.encrypt('test.pdf', options);

it gives me this error.

**Comment by nrhirani** [comment]
Looks like the path for the `test.pdf` is not give correctly. Can you give absolute path for the PDF and check?

**Comment by imranmunirawan** [comment]
my existence is in the same directory , i did try even passing up the absolute paths and relative paths

**Comment by GodsBest** [comment]
Here is the complete error returned within the callback:

```
[
  Error: spawn qpdf ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
      at onErrorNT (internal/child_process.js:470:16)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    errno: 'ENOENT',
    code: 'ENOENT',
    syscall: 'spawn qpdf',
    path: 'qpdf',
    spawnargs: [
      '--encrypt',
      'pa55w0rd',
      'pa55w0rd',
      256,
      '--print=full',
      '--modify=none',
      '--extract=n',
      '--accessibility=y',
      '--',
      'sourcePath.pdf',
      'destinationPath.pdf'
    ]
  }
]
```

So, what's really going on here?

**Comment by krishna066** [comment]
Error: spawn qpdf ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn qpdf',
  path: 'qpdf',
  spawnargs: [
    '--encrypt',
    '1234',
    '1234',
    '256',
    '--',
    '/testll.pdf',
    '/test2.pdf'
  ]
}

I'm getting this error, while encrypting the PDF with node-qpdf2 package.
Also, I checked the path it is correct.

**Comment by alfaz151** [comment]
Any solution to the above error??

**Comment by anndreyy** [comment]
In my case, which I was running on macOS, the problem was quite simple. I didn't have qpdf installed on the computer.
To install, just run the command below in the terminal:
`brew install qpdf`
The node-qpdf library could check if qpdf is installed and throw an exception, but it doesn't do that.

**Comment by rajesh460** [comment]
> Error: spawn qpdf ENOENT at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19) at onErrorNT (internal/child_process.js:469:16) at processTicksAndRejections (internal/process/task_queues.js:82:21) { errno: -2, code: 'ENOENT', syscall: 'spawn qpdf', path: 'qpdf', spawnargs: [ '--encrypt', '1234', '1234', '256', '--', '/testll.pdf', '/test2.pdf' ] }
> 
> I'm getting this error, while encrypting the PDF with node-qpdf2 package. Also, I checked the path it is correct.

For this Need to Download QPDF Application in Local Machine
