### ISSUE TITLE
Package version issue

### ISSUE THREAD

**Issue by hekkim** [nrhirani/node-qpdf#4]
Hi,

I recently download it through NPM on my project.
But, it does not reflect changes that was changed in newest version of code.

For example, there is no option in `encrypt()` for `outputPath` on my package.

It looks like NPM does not bring most recent version of code.

Please let me know if you have any question.

Thanks,

**Comment by nrhirani** [comment]
Hi, @hekkim I have not released a package after the changes merged into master. I'll publish this in few hours.

**Comment by hekkim** [comment]
lol

You left the answers just right after I posted it.
Thank you so much :)

**Comment by nrhirani** [comment]
I have published a new version.
