### ISSUE TITLE
Document/Example is not is sync

### ISSUE THREAD

**Issue by nbaua** [nrhirani/node-qpdf#5]
For example 

`qpdf.decrypt(localFilePath, 'YOUR_PASSWORD_TO_DECRYPT_PDF');
`

should have been updated to something like

`qpdf.decrypt(localFilePath, 'YOUR_PASSWORD_TO_DECRYPT_PDF',callback);`

The saving decrypted file is not working either due to this.

**Comment by nrhirani** [comment]
@nbaua The callback can be explained via the example below

`qpdf.decrypt(localFilePath, 'YOUR_PASSWORD_TO_DECRYPT_PDF', outputFilePath);`

Hope that helps.

**Comment by nbaua** [comment]
The above code still requires the callback.
I don't see any override here which accepts both callback and the outputFilePath.
May be I am not sure, how can I decrypt the file and save the same file without the password in another folder on server?

-- N Baua

**Comment by jsanko9** [comment]
Hi,
I had the same problem, 3rd argument in decrypt function is not accepting string of file path, but it requires callback function, to in which it will not return data. Luckily I did not need this argument at the end. But the documentation is really not correct in this part. Tested with 1.0.3 and 1.0.0
