### ISSUE TITLE
Example of the callback function for the third argument

### ISSUE THREAD

**Issue by waynellin** [nrhirani/node-qpdf#9]
qpdf.encrypt(localFilePath, options, outputFilePath);
and qpdf.decrypt(localFilePath, 'YOUR_PASSWORD_TO_DECRYPT_PDF', outputFilePath);
requires callback for outputFilePath. Where do we actually provide the string for output location? and what's an example for the callback function?

**Comment by andreaswk** [comment]
Here is a working example using the callback argument:
`
const fs = require('fs');
const path = require('path');

var options = {
  keyLength: 40,
  password: 'STRONG'
};
qpdf.encrypt('./sample.pdf', options, function(err, data) {
  if (err) {
    console.log(err);
  } else {
    const writeStream = fs.createWriteStream('./secured.pdf');
    data.pipe(writeStream);
  }
});
`
